# Generated by Django 4.2.9 on 2024-01-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=800, verbose_name='邮件名')),
                ('user_name', models.CharField(blank=True, max_length=800, null=True, verbose_name='邮箱用户名')),
                ('password', models.CharField(blank=True, max_length=800, null=True, verbose_name='邮箱密码')),
                ('email_host', models.CharField(blank=True, max_length=800, null=True, verbose_name='SMTP服务器主机')),
                ('email_ttls', models.BooleanField(blank=True, null=True, verbose_name='ttls')),
                ('email_port', models.IntegerField(blank=True, null=True, verbose_name='端口')),
                ('email_type', models.CharField(blank=True, choices=[('send', '发送邮件'), ('cc', '抄送的邮件')], max_length=80, null=True, verbose_name='邮件类型')),
            ],
            options={
                'verbose_name': '发邮件信息信息',
                'verbose_name_plural': '发邮件信息信息',
                'db_table': 'app_user_email_info',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(max_length=30, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'db_table': 'app_user_email_varify_record',
            },
        ),
        migrations.CreateModel(
            name='SystemRuntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_runtime', models.FloatField(default=0, verbose_name='总运行时间(秒)')),
                ('hold_runtime', models.FloatField(default=180, verbose_name='可运行时间(天)')),
            ],
            options={
                'verbose_name': '运行时间',
                'verbose_name_plural': '运行时间',
                'db_table': 'app_user_runtime',
            },
        ),
    ]
